name: Backend CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: self-hosted

    # Make secrets available to all steps
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      PORT: ${{ secrets.PORT }}

    strategy:
      matrix:
        node-version: [22]  # works, but ensure your runner can download/install it

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Enable Corepack (Yarn)
        run: corepack enable

      # --- Backend ---
      - name: Create backend .env
        working-directory: ./backend
        run: |
          cat > .env <<EOF
          MONGO_URI=${MONGO_URI}
          JWT_SECRET=${JWT_SECRET}
          PORT=${PORT}
          EOF

      - name: Install backend deps
        working-directory: ./backend
        run: yarn install --frozen-lockfile

      - name: Run backend tests
        working-directory: ./backend
        run: yarn test --ci

      # --- Frontend (optional if you only care about backend CI) ---
      - name: Install frontend deps
        working-directory: ./frontend
        run: yarn install --frozen-lockfile

      - name: Build frontend
        working-directory: ./frontend
        run: yarn build
